# Generated by Django 4.1.2 on 2022-10-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="title", field=models.CharField(max_length=150),
        ),
    ]
